### ISSUE TITLE
Invalid json response body at https://api.play.ht/api/v2/leases

### ISSUE THREAD

**Issue by Fujiwaranosai** [playht/playht-nodejs-sdk#18]
This error is thrown every day and my app is crashed:

```
2024-01-08 13:29:59.141 +00:00: FetchError: invalid json response body at https://api.play.ht/api/v2/leases reason: Unexpected token < in JSON at position 0
2024-01-08 13:29:59.141 +00:00:     at /home/ubuntu/test-server/node_modules/playht/dist/cjs/index.js:23923:40
2024-01-08 13:29:59.141 +00:00:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-01-08 13:29:59.141 +00:00:     at Client.getLease (/home/ubuntu/test-server/node_modules/playht/dist/cjs/index.js:37091:28)
2024-01-08 13:29:59.141 +00:00:     at Client.refreshLease (/home/ubuntu/test-server/node_modules/playht/dist/cjs/index.js:37110:18)
```

I'm not sure why it happened and how to handle it. Can someone please help?

**Comment by NCarrollPlay** [comment]
We're working on a fix for this on our side. We'll have a new release that should address it soon.
