### ISSUE TITLE
Cannot iterate over a consumed stream while running the gpt-example

### ISSUE THREAD

**Issue by AksAman** [playht/playht-nodejs-sdk#8]
I am trying to run the gpt-example, but when requesting at the `/say-prompt` endpoint, the server throws following error:

```
file:///{path}/playht-nodejs-sdk/packages/gpt-example/server/node_modules/openai/streaming.mjs:34
                throw new Error('Cannot iterate over a consumed stream, use `.tee()` to split the stream.');
                      ^

Error: Cannot iterate over a consumed stream, use `.tee()` to split the stream.
    at Stream.iterator (file:///{path}/playht-nodejs-sdk/packages/gpt-example/server/node_modules/openai/streaming.mjs:34:23)
    at iterator.next (<anonymous>)
    at Readable.<anonymous> (file:///{path}/playht-nodejs-sdk/packages/gpt-example/server/dist/streamGptText.js:40:194)
    at Generator.next (<anonymous>)
    at file:///{path}/playht-nodejs-sdk/packages/gpt-example/server/dist/streamGptText.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (file:///{path}/playht-nodejs-sdk/packages/gpt-example/server/dist/streamGptText.js:3:12)
    at Readable.read [as _read] (file:///{path}/playht-nodejs-sdk/packages/gpt-example/server/dist/streamGptText.js:38:24)
    at Readable.read (node:internal/streams/readable:507:12)
    at maybeReadMore_ (node:internal/streams/readable:661:12)

Node.js v18.18.2
error: script "start" exited with code 1 (SIGHUP)
error: script "start" exited with code 1 (SIGHUP)
```

Note: I had to update `playht` to ` "^0.9.3"` from `"0.9.0-beta"`, else it was showing error `.stream` is not a method

**Comment by houareau** [comment]
Im having the same issue even using 0.9.3.

**Comment by bhamlefty** [comment]
Yup same issue here with  "openai": "^4.20.1" "playht": "^0.9.6"

**Comment by ServicesNowGroup** [comment]
Same issue using chatgpt 3.5 turbo and playht 2 turbo
